FROM python:3.9

WORKDIR /src
COPY . .

# 라이브러리 설치
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libosmesa6 \
    libosmesa6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

ENV PYOPENGL_PLATFORM=osmesa
ENV ENV=dev

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]