FROM openjdk:17-jdk-slim-buster
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=build/libs/whiskeywiki-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","/app.jar"]
ENV TZ=Asia/Seoul
RUN apt-get install -y tzdata